/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.com.gestioninventario.presentacion;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.com.gestioninventario.basedatos.CategoriaDAO;
import pe.com.gestioninventario.entidades.Categoria;

/**
 *
 * @author pz
 */
public class FrmGestionCategoria extends javax.swing.JInternalFrame {

  /**
   * Creates new form FrmGestionCategoria
   */
  public FrmGestionCategoria() {
    initComponents();
    this.setSize(600, 400);
    this.setTitle("Gestión de Categorías");
    cargarTabla();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_categoria = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_categoria = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idCategoria", "Categoria", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_categoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_categoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(102, 102, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Categoria:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txt_nombre_categoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.add(txt_nombre_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, 130, 30));

        btn_actualizar.setBackground(new java.awt.Color(153, 255, 204));
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        btn_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 190, 250));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/fondo_pantalla1.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
     if(txt_nombre_categoria.getText().isEmpty()){
       JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de categoria");
      }else{
        int idCategoria = Integer.parseInt(tabla_categoria.getValueAt(tabla_categoria.getSelectedRow(), 0).toString());
        String nombre = txt_nombre_categoria.getText();
        Categoria categoria = new Categoria(idCategoria, nombre);
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        try {
          categoriaDAO.actualizarCategoria(categoria);
          cargarTabla();
          limpiar();
          
          JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
        } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(null, "Error al actualizar registro");
        }
      }
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
      int fila = tabla_categoria.getSelectedRow();
      if(fila == -1){
        JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
      }else{
        int idCategoria = Integer.parseInt(tabla_categoria.getValueAt(fila, 0).toString());
        Categoria categoria = new Categoria(idCategoria);
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        try {
          categoriaDAO.eliminarCategoria(categoria);
          cargarTabla();
          limpiar();
          JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
        } catch (Exception e) {
          e.printStackTrace();
          JOptionPane.showMessageDialog(null, "Error al eliminar registro");
        }
      }
    }//GEN-LAST:event_btn_eliminarActionPerformed

  private void tabla_categoriaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable_categoriaMouseClicked

    CategoriaDAO categoriaDAO = new CategoriaDAO();
    int fila = tabla_categoria.getSelectedRow();
    int idCategoria = Integer.parseInt(tabla_categoria.getValueAt(fila, 0).toString());
    Categoria categoria = new Categoria(idCategoria);
    try {
      categoria = categoriaDAO.buscarCategoria(categoria);
      txt_nombre_categoria.setText(categoria.getNombre());
    } catch (Exception e) {
      e.printStackTrace();
      JOptionPane.showMessageDialog(null, "Error al seleccionar registro");
    }

  }// GEN-LAST:event_jTable_categoriaMouseClicked

  // cargar tabla
   public void cargarTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tabla_categoria.getModel();
    modeloTabla.setRowCount(0);
    CategoriaDAO categoriaDAO = new CategoriaDAO();
    try {
      List<Categoria> categorias = categoriaDAO.mostrarCategoria();
      
      for (Categoria categoria : categorias) {
        Object[] registro = { categoria.getIdCategoria(), categoria.getNombre(), categoria.getEstado() };
        modeloTabla.addRow(registro);

      }
      tabla_categoria.setModel(modeloTabla);
    } catch (Exception e) {
      e.printStackTrace();
    }

  }
  //metodo LImpiar
  public void limpiar(){
    txt_nombre_categoria.setText("");
  }



  

  //

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_categoria;
    private javax.swing.JTextField txt_nombre_categoria;
    // End of variables declaration//GEN-END:variables
}
