package pe.com.gestioninventario.presentacion;

import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

import pe.com.gestioninventario.basedatos.ProductoDAO;
import pe.com.gestioninventario.entidades.Producto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ediso
 */
public class FrmGestionarProducto extends javax.swing.JInternalFrame {

  public FrmGestionarProducto() {
    initComponents();
    this.setSize(new Dimension(900, 500));
    this.setTitle("Gestionar Productos");
    cargarTabla();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_categoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_nombre1 = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        ComboBox_marca = new javax.swing.JComboBox<>();
        ComboBox_estado1 = new javax.swing.JComboBox<>();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Descripción", "Precio", "Cantidad", "Categoria", "Marca", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 130, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setEnabled(false);
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Marca");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cantidad");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Estado");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categoria:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, -1));

        ComboBox_categoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urbano", "Correr", "Futbol", "Entrenar" }));
        jPanel3.add(ComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Descripcion");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombre:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));
        jPanel3.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 170, -1));
        jPanel3.add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, -1));
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, -1));
        jPanel3.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 170, -1));

        ComboBox_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike", "Adidas" }));
        jPanel3.add(ComboBox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 170, -1));

        ComboBox_estado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboBox_estado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible", "En stock", "Agotado" }));
        jPanel3.add(ComboBox_estado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 120));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/fondomediano4.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_productosMouseClicked(java.awt.event.MouseEvent evt) {    
      
    int fila = tabla_productos.getSelectedRow();
    if (fila == -1) {
      JOptionPane.showMessageDialog(this, "Seleccione un producto");
    } else {
      int id = Integer.parseInt(tabla_productos.getValueAt(fila, 0).toString());
      String nombre = tabla_productos.getValueAt(fila, 1).toString();
      String descripcion = tabla_productos.getValueAt(fila, 2).toString();
      String precio = tabla_productos.getValueAt(fila, 3).toString();
      String cantidad = tabla_productos.getValueAt(fila, 4).toString();
      String categoria = tabla_productos.getValueAt(fila, 5).toString();
      String marca = tabla_productos.getValueAt(fila, 6).toString();
      String estado = tabla_productos.getValueAt(fila, 7).toString();
      txt_id.setText(id + "");
      txt_nombre1.setText(nombre);
      txt_descripcion.setText(descripcion);
      txt_precio.setText(precio);
      txt_cantidad.setText(cantidad);
      ComboBox_marca.setSelectedItem(marca);
      ComboBox_categoria.setSelectedItem(estado);
      ComboBox_categoria.setSelectedItem(categoria);
    }
    

         
         
                                                   
    }                                            

    
   // cargarTabla

  public void cargarTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tabla_productos.getModel();
    modeloTabla.setRowCount(0);
   
    ProductoDAO productoDAO = new ProductoDAO();
    try {
      List<Producto> productos = productoDAO.mostrarProducto();
      for (Producto producto : productos) {
        Object[] fila = {producto.getId()+ "", producto.getNombre(), producto.getDescripcion(), producto.getPrecio()+"",
            producto.getCantidad()+"", producto.getCategoria(), producto.getMarca(), producto.getEstado()};
        modeloTabla.addRow(fila);
      }

    } catch (Exception e) {
      e.printStackTrace();
      JOptionPane.showMessageDialog(this, "Error al cargar tabla");

    }

  }

  private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_actualizarActionPerformed
    ProductoDAO productoDAO = new ProductoDAO();
    int fila = tabla_productos.getSelectedRow();
    if (fila == -1) {
      JOptionPane.showMessageDialog(this, "Seleccione un producto");
    } else {
      int id = Integer.parseInt(txt_id.getText());
      String nombre = txt_nombre1.getText();
      String descripcion = txt_descripcion.getText();
      double precio = Double.parseDouble(txt_precio.getText());
      int cantidad = Integer.parseInt(txt_cantidad.getText());
      String categoria = ComboBox_categoria.getSelectedItem().toString();
      String marca = ComboBox_marca.getSelectedItem().toString();
      String estado = ComboBox_estado1.getSelectedItem().toString();
      Producto producto = new Producto(id, nombre, descripcion, precio, cantidad, categoria, marca, estado);
      try {
        productoDAO.actualizarProducto(producto);
        JOptionPane.showMessageDialog(this, "Producto actualizado correctamente");
        cargarTabla();
        limpiarCampos();
      } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al actualizar producto");
      }
    }
   
  }// GEN-LAST:event_btn_actualizarActionPerformed

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_eliminarActionPerformed
    ProductoDAO productoDAO = new ProductoDAO();
    int fila = tabla_productos.getSelectedRow();
    if (fila == -1) {
      JOptionPane.showMessageDialog(this, "Seleccione un producto");
    } else {
      int id = Integer.parseInt(tabla_productos.getValueAt(fila, 0).toString());
      Producto producto = new Producto(id);
      try {
        productoDAO.eliminarProducto(producto);
        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente");
        cargarTabla();
      } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al eliminar producto");
      }
    }
  }// GEN-LAST:event_btn_eliminarActionPerformed

  //limpiar campos
  public void limpiarCampos() {
    txt_id.setText("");
    txt_nombre1.setText("");
    txt_descripcion.setText("");
    txt_precio.setText("");
    txt_cantidad.setText("");
    ComboBox_marca.setSelectedIndex(0);
    ComboBox_categoria.setSelectedIndex(0);
    ComboBox_estado1.setSelectedIndex(0);
   
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_categoria;
    private javax.swing.JComboBox<String> ComboBox_estado1;
    private javax.swing.JComboBox<String> ComboBox_marca;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla_productos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

}