/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.com.gestioninventario.presentacion;

import javax.swing.JOptionPane;

import pe.com.gestioninventario.basedatos.CategoriaDAO;
import pe.com.gestioninventario.entidades.Categoria;

/**
 *
 * @author pz
 */
public class FrmInterCategoria extends javax.swing.JInternalFrame {

  /**
   * Creates new form FrmInterCategoria
   */
  public FrmInterCategoria() {
    initComponents();
    this.setSize(400, 200);
    this.setTitle("Nueva Categoría");

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txt_nombre_categoria = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel_wallpaper = new javax.swing.JLabel();

    setClosable(true);
    setIconifiable(true);
    setResizable(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nueva Categoria");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Nombre Categoria");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
    getContentPane().add(txt_nombre_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, -1));

    jButton1.setBackground(new java.awt.Color(0, 204, 204));
    jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
    jButton1.setText("Crear");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, -1));

    jLabel_wallpaper.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
    jLabel_wallpaper.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/fondo_pantalla1.jpg"))); // NOI18N
    getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

    FrmGestionCategoria frmGestionCategoria = new FrmGestionCategoria();
    // Crear nueva categoria
    Categoria categoria = new Categoria();
    CategoriaDAO categoriaDAO = new CategoriaDAO();
    // 1. Recuperar el nombre de la categoria

    String nombreCategoria = txt_nombre_categoria.getText().trim();

    // 2. Validar que el nombre de la categoria no sea vacio
    // valida que se astring

    if (nombreCategoria.isEmpty()) {
      JOptionPane.showMessageDialog(null, "El nombre de la categoria no puede estar vacio");

    } else {
      try {
        // 3. Validar que la categoria no exista
      
        if (categoriaDAO.existeCategoria(nombreCategoria) == false) {

          System.out.println("La categoria no existe"+categoriaDAO.existeCategoria(nombreCategoria));
          categoria.setNombre(nombreCategoria);
          categoria.setEstado("Habilitado");
          categoria.setFechaCreacion(new java.sql.Date(System.currentTimeMillis()));
          categoriaDAO.insertarCategoria(categoria);
          frmGestionCategoria.cargarTabla();
          txt_nombre_categoria.setText("");

          JOptionPane.showMessageDialog(null, "Categoria creada correctamente");
        } else {
          JOptionPane.showMessageDialog(null, "La categoria ya existe");


        }

      } catch (Exception e) {

        e.printStackTrace();
        System.out.println("Error al insertar categoria" + e.getMessage());
      }

      // 6. Mostrar mensaje de exito

    }
    


  }// GEN-LAST:event_jButton1ActionPerformed

  //cargarTabla();



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel_wallpaper;
  private javax.swing.JTextField txt_nombre_categoria;
  // End of variables declaration//GEN-END:variables
}
