/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.com.gestioninventario.presentacion;

import java.util.ArrayList;
import java.util.Random;

import javax.swing.JOptionPane;

import pe.com.gestioninventario.basedatos.Login;
import pe.com.gestioninventario.entidades.Usuario;

/**
 *
 * @author pz
 */
public class FrmLogin extends javax.swing.JFrame {
  private int intentos = 0;

  /**
   * Creates new form FrmLogin
   */
  public FrmLogin() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bg = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    titulo = new javax.swing.JLabel();
    icono = new javax.swing.JLabel();
    tituloZapatilla = new javax.swing.JLabel();
    iniciarSesionLabel = new javax.swing.JLabel();
    usuarioLabel = new javax.swing.JLabel();
    usuarioText = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    passwordLabel = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    passwordTxt = new javax.swing.JPasswordField();
    btnIngresar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setLocationByPlatform(true);
    setResizable(false);

    bg.setBackground(new java.awt.Color(255, 255, 255));
    bg.setForeground(new java.awt.Color(51, 51, 51));
    bg.setToolTipText("");
    bg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(51, 255, 204));

    titulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
    titulo.setForeground(new java.awt.Color(255, 51, 51));
    titulo.setText("Gestion de Inventario");

    icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/zapatos.png"))); // NOI18N

    tituloZapatilla.setBackground(new java.awt.Color(255, 255, 255));
    tituloZapatilla.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
    tituloZapatilla.setForeground(new java.awt.Color(204, 0, 0));
    tituloZapatilla.setText("ZAPATILLAS");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(tituloZapatilla)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(icono)
                .addContainerGap(25, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(titulo)
                .addGap(75, 75, 75)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(tituloZapatilla, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE)));

    bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

    iniciarSesionLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
    iniciarSesionLabel.setText("INICIAR SESIÓN");
    bg.add(iniciarSesionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

    usuarioLabel.setText("USUARIO");
    bg.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

    usuarioText.setForeground(new java.awt.Color(51, 51, 51));
    usuarioText.setBorder(null);
    bg.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 390, 30));

    jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
    bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 390, 20));

    passwordLabel.setText("PASSWORD");
    bg.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, 20));
    bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

    jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
    bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 400, 10));

    passwordTxt.setBorder(null);
    bg.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 410, -1));

    btnIngresar.setBackground(new java.awt.Color(51, 255, 204));
    btnIngresar.setText("INGRESAR");
    btnIngresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresarActionPerformed(evt);
      }
    });
    bg.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 98, 28));

    btnCancelar.setBackground(new java.awt.Color(255, 0, 153));
    btnCancelar.setText("CANCELAR");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });
    bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 100, 30));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIngresarActionPerformed

    String usuario = usuarioText.getText();
    String clave = new String(passwordTxt.getPassword());

    Login login = new Login();
    ArrayList<Usuario> usuarioValidado = login.login(usuario, clave);
    validarCanpos(usuario, clave, usuarioValidado);

  }// GEN-LAST:event_btnIngresarActionPerformed

  // validar Campos
  public void validarCanpos(String usuario, String clave, ArrayList<Usuario> usuarioValidado) {
    if (usuario.isEmpty() || clave.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Campos en blanco debe ingresar usuario y clave");
      return;

    }
    if (usuarioValidado == null || usuarioValidado.isEmpty()) {
      intentos++;
      JOptionPane.showMessageDialog(null, "Usuario o clave incorrecta");
      Random random = new Random();
      if (intentos >= 3) {
        int num1 = random.nextInt(10) + 1;
        int num2 = random.nextInt(10) + 1;
        JOptionPane.showMessageDialog(null, "A exedido el numero de intentos, debe resolver una suma para continuar");
        String respuesta = JOptionPane.showInputDialog(null, "Resuelva la siguiente suma: " + num1 + " + " + num2);
        try {
          int suma = Integer.parseInt(respuesta);
          if (suma == num1 + num2) {
            JOptionPane.showMessageDialog(null, "Suma correcto");
            usuarioText.setEnabled(true);
            passwordTxt.setEnabled(true);
            usuarioText.setText("");
            passwordTxt.setText("");
            intentos = 0;
          } else {
            intentos++;
            JOptionPane.showMessageDialog(null, "Suma incorrecto");
            usuarioText.setEnabled(false);
            passwordTxt.setEnabled(false);

            return;
          }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Debe ingresar un numero");
          usuarioText.setEnabled(false);
          passwordTxt.setEnabled(false);
        }

      }

    } else {
      /// validar estado
      if (usuarioValidado.get(0).getEstado().equals("Deshabilitado")) {
        JOptionPane.showMessageDialog(null, "Usuario deshabilitado");
        return;
      } else {
        this.setVisible(false);
        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setExtendedState(frmPrincipal.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        frmPrincipal.setVisible(true);

        intentos = 0;

      }
    }

  }

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed

    this.dispose();
  }// GEN-LAST:event_btnCancelarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmLogin().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bg;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnIngresar;
  private javax.swing.JLabel icono;
  private javax.swing.JLabel iniciarSesionLabel;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField passwordTxt;
  private javax.swing.JLabel titulo;
  private javax.swing.JLabel tituloZapatilla;
  private javax.swing.JLabel usuarioLabel;
  private javax.swing.JTextField usuarioText;
  // End of variables declaration//GEN-END:variables
}
