/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.com.gestioninventario.presentacion;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;

import pe.com.gestioninventario.entidades.Usuario;


/**
 *
 * @author pz
 */
public class FrmPrincipal extends javax.swing.JFrame {

  public static JPanel panel;

  /**
   * Creates new form FrmPrincipal
   */
  public FrmPrincipal() {
    initComponents();
    this.setSize(new Dimension(1200, 700));
    this.setExtendedState(this.MAXIMIZED_BOTH);
    this.setLocationRelativeTo(null);
    this.setTitle("Sistema de Inventario Zapatillas");
    this.setLayout(null);
    // verde limon

    panel = new JPanel();
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    panel.setBounds(0, 0, ancho, (alto - 110));
    this.add(panel);
    // modificar color de fondo
    panel.setBackground(new java.awt.Color(204, 255, 255));

    this.setVisible(true);

  }

  FrmPrincipal(ArrayList<Usuario> usuarioValidado) {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                   // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_gestion_personas = new javax.swing.JMenuItem();
        jMenuItem_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem_gestion_usuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem_gestion_cliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_nuevo_proveedor = new javax.swing.JMenuItem();
        jMenuItem_gestion_proveedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem_gestion_producto = new javax.swing.JMenuItem();
        jMenuItem_actualizar_stock = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_reporte_cliente = new javax.swing.JMenuItem();
        jMenuItem_reporte_categoria = new javax.swing.JMenuItem();
        jMenuItem_reporte_producto = new javax.swing.JMenuItem();
        jMenuItem_reporte_ventas = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Inventario Zapatillas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/users_25329.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_gestion_personas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/equipo.png"))); // NOI18N
        jMenuItem_gestion_personas.setText("Gestionar Persona");
        jMenuItem_gestion_personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestion_personasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_gestion_personas);

        jMenuItem_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/agregar-usuario.png"))); // NOI18N
        jMenuItem_nuevo_usuario.setText("Nuevo Usuario");
        jMenuItem_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_nuevo_usuario);

        jMenuItem_gestion_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/gestionUsuario.png"))); // NOI18N
        jMenuItem_gestion_usuario.setText("Gestionar Usuario");
        jMenuItem_gestion_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestion_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_gestion_usuario);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/agregar-cliente.png"))); // NOI18N
        jMenuItem_nuevo_cliente.setText("Nuevo Cliente");
        jMenu3.add(jMenuItem_nuevo_cliente);

        jMenuItem_gestion_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/gestion-de-la-relacion-con-el-cliente.png"))); // NOI18N
        jMenuItem_gestion_cliente.setText("Gestion Cliente");
        jMenu3.add(jMenuItem_gestion_cliente);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/proveedor.png"))); // NOI18N
        jMenu5.setText("Proveedor");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_nuevo_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/proveedornuevo.png"))); // NOI18N
        jMenuItem_nuevo_proveedor.setText("Nuevo Proveedor");
        jMenu5.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestion_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/cadena-de-suministro.png"))); // NOI18N
        jMenuItem_gestion_proveedor.setText("Gestion de Proveedor");
        jMenuItem_gestion_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestion_proveedorActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_gestion_proveedor);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/zapatos-para-correr.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/agregarProducto.png"))); // NOI18N
        jMenuItem_nuevo_producto.setText("Nuevo Producto");
        jMenuItem_nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_nuevo_producto);

        jMenuItem_gestion_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/gestion-de-producto.png"))); // NOI18N
        jMenuItem_gestion_producto.setText("Gestionar producto");
        jMenuItem_gestion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestion_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestion_producto);

        jMenuItem_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/agregar-archivo.png"))); // NOI18N
        jMenuItem_actualizar_stock.setText("Actualizar Stock");
        jMenu2.add(jMenuItem_actualizar_stock);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/opciones.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/agregarCategoria.png"))); // NOI18N
        jMenuItem_nueva_categoria.setText("Nueva Categoria");
        jMenuItem_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_nueva_categoria);

        jMenuItem_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/gestion-de-carpetas.png"))); // NOI18N
        jMenuItem_gestionar_categoria.setText("Gestionar Categoria");
        jMenuItem_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionar_categoria);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/transaccion.png"))); // NOI18N
        jMenu6.setText("Transacciones");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(133, 50));
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/ordenes.png"))); // NOI18N
        jMenu7.setText("Ordenes");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(133, 50));
        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/informe-seo.png"))); // NOI18N
        jMenu8.setText("Informes");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem_reporte_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/reporte.png"))); // NOI18N
        jMenuItem_reporte_cliente.setText("Reporte Clientes");
        jMenuItem_reporte_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reporte_clienteActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_reporte_cliente);

        jMenuItem_reporte_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/reporteCategoria.png"))); // NOI18N
        jMenuItem_reporte_categoria.setText("Reporte Categorias");
        jMenuItem_reporte_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reporte_categoriaActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_reporte_categoria);

        jMenuItem_reporte_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/reporteProductos.png"))); // NOI18N
        jMenuItem_reporte_producto.setText("Reporte Productos");
        jMenu8.add(jMenuItem_reporte_producto);

        jMenuItem_reporte_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/grafico-de-barras.png"))); // NOI18N
        jMenuItem_reporte_ventas.setText("Reporte Ventas");
        jMenuItem_reporte_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reporte_ventasActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_reporte_ventas);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenu9.setText("Salir");
        jMenu9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(133, 50));

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/gestioninventario/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItem19.setText("Salir");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_gestion_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestion_usuarioActionPerformed
        FrmGestionUsuarios frmGestionUsuarios = new FrmGestionUsuarios();
        panel.add(frmGestionUsuarios);
        frmGestionUsuarios.setVisible(true);
        


    }//GEN-LAST:event_jMenuItem_gestion_usuarioActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem_nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_productoActionPerformed
        FrmInterProducto frmInterProducto = new FrmInterProducto();
        panel.add(frmInterProducto);
        frmInterProducto.setVisible(true);  
    }//GEN-LAST:event_jMenuItem_nuevo_productoActionPerformed

    private void jMenuItem_gestion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestion_productoActionPerformed
        FrmGestionarProducto frmGestionProducto = new FrmGestionarProducto();
        panel.add(frmGestionProducto);
        frmGestionProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestion_productoActionPerformed

  private void jMenuItem_gestion_proveedorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_gestion_proveedorActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jMenuItem_gestion_proveedorActionPerformed

  private void jMenuItem_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_gestionar_categoriaActionPerformed

    FrmGestionCategoria frmGestionCategoria = new FrmGestionCategoria();
    panel.add(frmGestionCategoria);
    frmGestionCategoria.setVisible(true);

  }// GEN-LAST:event_jMenuItem_gestionar_categoriaActionPerformed

  private void jMenuItem_reporte_categoriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_reporte_categoriaActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jMenuItem_reporte_categoriaActionPerformed

  private void jMenuItem_reporte_ventasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_reporte_ventasActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jMenuItem_reporte_ventasActionPerformed

  private void jMenuItem_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_nuevo_usuarioActionPerformed
    FrmInterUsuario frmInterUsuario = new FrmInterUsuario();
    panel.add(frmInterUsuario);
    frmInterUsuario.setVisible(true);
  }// GEN-LAST:event_jMenuItem_nuevo_usuarioActionPerformed

  private void jMenuItem_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_nueva_categoriaActionPerformed
    
    FrmInterCategoria frmInterCategoria = new FrmInterCategoria();
    panel.add(frmInterCategoria);
    frmInterCategoria.setVisible(true);

  }// GEN-LAST:event_jMenuItem_nueva_categoriaActionPerformed

  private void jMenuItem_reporte_clienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_reporte_clienteActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_jMenuItem_reporte_clienteActionPerformed

  private void jMenuItem_gestion_personasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_gestion_personasActionPerformed
    FrmGestionPersonas frmGestionPersonas = new FrmGestionPersonas();
    panel.add(frmGestionPersonas);
    frmGestionPersonas.setVisible(true);

  }// GEN-LAST:event_jMenuItem_gestion_personasActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrmPrincipal().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_actualizar_stock;
    private javax.swing.JMenuItem jMenuItem_gestion_cliente;
    private javax.swing.JMenuItem jMenuItem_gestion_personas;
    private javax.swing.JMenuItem jMenuItem_gestion_producto;
    private javax.swing.JMenuItem jMenuItem_gestion_proveedor;
    private javax.swing.JMenuItem jMenuItem_gestion_usuario;
    private javax.swing.JMenuItem jMenuItem_gestionar_categoria;
    private javax.swing.JMenuItem jMenuItem_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem_nuevo_cliente;
    private javax.swing.JMenuItem jMenuItem_nuevo_producto;
    private javax.swing.JMenuItem jMenuItem_nuevo_proveedor;
    private javax.swing.JMenuItem jMenuItem_nuevo_usuario;
    private javax.swing.JMenuItem jMenuItem_reporte_categoria;
    private javax.swing.JMenuItem jMenuItem_reporte_cliente;
    private javax.swing.JMenuItem jMenuItem_reporte_producto;
    private javax.swing.JMenuItem jMenuItem_reporte_ventas;
    // End of variables declaration//GEN-END:variables
}
